title: Ilgsson Braga
author: IlgssonBraga
email: contato@ilgssonbraga.com.br
content: Ilgsson Braga
description: > # this means to ignore newlines until "show_exerpts:"
  Desenvolvedor Node.js que está aprendendo Rust e gosta de jogar
  nas horas vagas
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /ilgssonbraga.github.io

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Ilgsson Braga
  tagline: Web Developer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false

  # generate social links in footer
  social_links:
    twitter: Ilgsson_Braga
    github: IlgssonBraga
    linkedIn: in/ilgsson-braga-de-morais-silva-62b213199

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
